from django.contrib import admin
from .models import Settings, Slider, History, Restaurant, Days, Special, Special_foods, Menu, Lunch, Dinner, Dessert, Drinks, Reservetion, Command, Commands, Opit, Blog
# Register your models here.
admin.site.register(Settings)
admin.site.register(Slider)
admin.site.register(History)
admin.site.register(Restaurant)
admin.site.register(Days)
admin.site.register(Special)
admin.site.register(Special_foods)
admin.site.register(Menu)
admin.site.register(Lunch)
admin.site.register(Dinner)
admin.site.register(Dessert)
admin.site.register(Drinks)
admin.site.register(Reservetion)
admin.site.register(Command)
admin.site.register(Commands)
admin.site.register(Opit)
admin.site.register(Blog)