# Generated by Django 3.2.20 on 2023-11-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Изображение слайдера')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок слайда')),
                ('description', models.TextField(verbose_name='Описание слайдера')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
