# Generated by Django 3.2.20 on 2023-11-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='history/', verbose_name='Изображение')),
                ('sec_image', models.ImageField(upload_to='history/', verbose_name='Заднее фото')),
                ('suptitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('second_desc', models.TextField(verbose_name='Второе описание')),
                ('propic', models.ImageField(upload_to='history_propic/', verbose_name='Фото Подпись')),
            ],
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
    ]
