# Generated by Django 3.2.20 on 2023-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20231119_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('suptitle', models.CharField(max_length=255, verbose_name='Подзагаловок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('days', models.BooleanField(verbose_name='A')),
            ],
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
    ]
