# Generated by Django 3.2.20 on 2023-11-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20231119_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='', upload_to='restaurant/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sec_image',
            field=models.ImageField(default='', upload_to='restaurant/', verbose_name='Заднее фото'),
        ),
    ]
