# Generated by Django 3.2.20 on 2023-11-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20231119_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('suptitle', models.CharField(max_length=255, verbose_name='Подзагаловок')),
            ],
            options={
                'verbose_name': 'Загаловок Специальных блюд',
                'verbose_name_plural': 'Загаловок Специальных блюд',
            },
        ),
        migrations.CreateModel(
            name='Special_foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='special_media/', verbose_name='Фото')),
                ('block_title', models.CharField(max_length=100, verbose_name='Загаловок Фотографии')),
                ('block_suptitle', models.CharField(max_length=100, verbose_name='Подзагаловок Фотографии')),
                ('block_price', models.CharField(max_length=100, verbose_name='Цена')),
                ('block_time', models.CharField(help_text='Завтрак, Обед, Ужин, Десерт', max_length=100, verbose_name='Тип блюдо')),
            ],
            options={
                'verbose_name': 'Специальные блюды',
                'verbose_name_plural': 'Специальные блюды',
            },
        ),
    ]
