# Generated by Django 3.2.20 on 2023-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_author_book_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('suptitle', models.CharField(max_length=100, verbose_name='Описание')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('img', models.ImageField(upload_to='Menu/', verbose_name='Фото')),
                ('new', models.BooleanField(verbose_name='Новое')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерт',
            },
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('suptitle', models.CharField(max_length=100, verbose_name='Описание')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('img', models.ImageField(upload_to='Menu/', verbose_name='Фото')),
                ('new', models.BooleanField(verbose_name='Новое')),
            ],
            options={
                'verbose_name': 'Ужин',
                'verbose_name_plural': 'Ужин',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('suptitle', models.CharField(max_length=100, verbose_name='Описание')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('img', models.ImageField(upload_to='Menu/', verbose_name='Фото')),
                ('new', models.BooleanField(verbose_name='Новое')),
            ],
            options={
                'verbose_name': 'Напитки',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('suptitle', models.CharField(max_length=100, verbose_name='Описание')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('img', models.ImageField(upload_to='Menu/', verbose_name='Фото')),
                ('new', models.BooleanField(verbose_name='Новое')),
            ],
            options={
                'verbose_name': 'Ланч',
                'verbose_name_plural': 'Ланч',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
