# Generated by Django 3.2.20 on 2023-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20231120_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('suptitle', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
        ),
    ]
