# Generated by Django 3.2.20 on 2023-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_reservetion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetion',
            name='date_guest',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservetion',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservetion',
            name='pers_guest',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservetion',
            name='time_guest',
            field=models.CharField(default='', max_length=100),
        ),
    ]
