# Generated by Django 3.2.20 on 2023-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_auto_20231120_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetion',
            name='date_guest',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservetion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservetion',
            name='pers_guest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservetion',
            name='time_guest',
            field=models.TimeField(),
        ),
    ]
