# Generated by Django 3.2.20 on 2023-11-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_auto_20231120_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetion',
            name='date_guest',
        ),
    ]
