# Generated by Django 3.2.20 on 2023-11-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_remove_reservetion_date_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservetion',
            name='pers_guest',
        ),
        migrations.RemoveField(
            model_name='reservetion',
            name='time_guest',
        ),
    ]
