# Generated by Django 3.2.20 on 2023-11-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_auto_20231120_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservetion',
            options={},
        ),
        migrations.RemoveField(
            model_name='reservetion',
            name='suptitle',
        ),
        migrations.RemoveField(
            model_name='reservetion',
            name='title',
        ),
    ]
