# Generated by Django 3.2.20 on 2023-11-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_auto_20231120_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='Commands',
        ),
        migrations.DeleteModel(
            name='Reservetion',
        ),
    ]
