# Generated by Django 3.2.20 on 2023-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_auto_20231120_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('suptitle', models.CharField(max_length=255, verbose_name='Подзагаловок')),
            ],
            options={
                'verbose_name': 'Название команды',
                'verbose_name_plural': 'Название команды',
            },
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='commands/', verbose_name='Фото повара')),
                ('name', models.CharField(max_length=100, verbose_name='Имя повара')),
                ('special', models.CharField(max_length=100, verbose_name='Специальность')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook ссылка')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter ссылка')),
                ('google', models.URLField(blank=True, verbose_name='google ссылка')),
                ('instagram', models.URLField(blank=True, verbose_name='instagram ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Reservetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('suptitle', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
            },
        ),
    ]
