# Generated by Django 3.2.20 on 2023-11-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_command_commands_reservetion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservetion',
            options={},
        ),
        migrations.RemoveField(
            model_name='commands',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='commands',
            name='google',
        ),
        migrations.RemoveField(
            model_name='commands',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='commands',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='reservetion',
            name='suptitle',
        ),
        migrations.RemoveField(
            model_name='reservetion',
            name='title',
        ),
    ]
