# Generated by Django 3.2.20 on 2023-11-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_auto_20231120_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='Command_title',
        ),
    ]
