# Generated by Django 3.2.20 on 2023-11-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_rename_command_command_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('suptitle', models.CharField(default='', max_length=255, verbose_name='Подзагаловок')),
            ],
            options={
                'verbose_name': 'Название команды',
                'verbose_name_plural': 'Название команды',
            },
        ),
        migrations.DeleteModel(
            name='Command_title',
        ),
        migrations.AlterModelOptions(
            name='reservetion',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AddField(
            model_name='commands',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook ссылка'),
        ),
        migrations.AddField(
            model_name='commands',
            name='google',
            field=models.URLField(blank=True, verbose_name='google ссылка'),
        ),
        migrations.AddField(
            model_name='commands',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='instagram ссылка'),
        ),
        migrations.AddField(
            model_name='commands',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter ссылка'),
        ),
        migrations.AddField(
            model_name='reservetion',
            name='suptitle',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='reservetion',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
        ),
    ]
