# Generated by Django 3.2.20 on 2023-11-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_auto_20231120_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('data', models.CharField(help_text='December 16, 2015 /  Food /  3 comments', max_length=255, verbose_name='Дата')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook ссылка')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter ссылка')),
                ('google', models.URLField(blank=True, verbose_name='google ссылка')),
                ('instagram', models.URLField(blank=True, verbose_name='instagram ссылка')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.AlterModelOptions(
            name='opit',
            options={'verbose_name': 'Опыт', 'verbose_name_plural': 'Опыты'},
        ),
    ]
